HOST: "223.71.234.58"
POST: 3306
UserName: "ggzdev12138"
PassWd: "ggDevZMima245353"
DBName: "zt_app_operate_manage"
ExcludeDBName: [information_schema,mysql,performance_schema,school,sys,test]
#包含的DB名称 如果配置该信息则只导出该DB内数据
IncludeDBName: [zt_app_operate_manage]

AUTHOR: zltdhr
ClassNamePrefix: ""
ClassNameSuffix: ""
PackageStruct: "com.zt.appoperatemanage.model"
PackageMapper: "com.zt.appoperatemanage.mapper"
PackageApi: "com.zt.appoperatemanage.api"
PackageFallback: "com.zt.appoperatemanage.fallback"

ApplicationName: "zt-appoperatemanage-server"

#类型转化<mysqlDataType:OtherType>
#TypeTranslate: {
#  #整数
#  bit: "\r\n    private Integer %s = 0; //%s\r\n",
#  tinyint: "\r\n    private Integer %s = 0; //%s\r\n",
#  smallint: "\r\n    private Integer %s = 0; //%s\r\n",
#  mediumint: "\r\n    private Integer %s = 0; //%s\r\n",
#  int: "\r\n    private Integer %s = 0; //%s\r\n",
#  bigint: "\r\n    private Long %s = 0L; //%s\r\n",
#
#  #浮点
#  float: "\r\n    private Float %s = 0F; //%s\r\n",
#  double: "\r\n    private Double %s = 0D; //%s\r\n",
#  decimal: "\r\n    private BigDecimal %s = new BigDecimal(0); //%s\r\n",
#
#  #字符串
#  char: "\r\n    private String %s; //%s\r\n",
#  varchar: "\r\n    private String %s; //%s\r\n",
#  tinytext: "\r\n    private String %s; //%s\r\n",
#  text: "\r\n    private String %s; //%s\r\n",
#  mediumtext: "\r\n    private String %s; //%s\r\n",
#  longtext: "\r\n    private String %s; //%s\r\n",
#
#  #日期时间
#  datetime: "\r\n    @Getter(onMethod_ = {@JsonSerialize(using = TimestampSerializer.class)})\r\n    private Date %s; //%s\r\n",
#}

#类型转化<mysqlDataType:OtherType>
TypeTranslate: {
  #整数
  bit: "\r\n    private Integer %s; //%s\r\n",
  tinyint: "\r\n    private Integer %s; //%s\r\n",
  smallint: "\r\n    private Integer %s; //%s\r\n",
  mediumint: "\r\n    private Integer %s; //%s\r\n",
  int: "\r\n    private Integer %s; //%s\r\n",
  bigint: "\r\n    private Long %s; //%s\r\n",

  #浮点
  float: "\r\n    private Float %s; //%s\r\n",
  double: "\r\n    private Double %s; //%s\r\n",
  decimal: "\r\n    private BigDecimal %s; //%s\r\n",

  #字符串
  char: "\r\n    private String %s; //%s\r\n",
  varchar: "\r\n    private String %s; //%s\r\n",
  tinytext: "\r\n    private String %s; //%s\r\n",
  text: "\r\n    private String %s; //%s\r\n",
  mediumtext: "\r\n    private String %s; //%s\r\n",
  longtext: "\r\n    private String %s; //%s\r\n",

  #日期时间
  datetime: "\r\n    @Getter(onMethod_ = {@JsonSerialize(using = TimestampSerializer.class)})\r\n    private Date %s; //%s\r\n",
}